//import parse from "html-react-parser";

//var gDrive = "https://drive.google.com/drive/folders/1d6QlunZ_zh-mTXB1H2u0C5DQC7Vjmq5U?usp=sharing";



var infoConferences = [

    {
        citation: "Popa, A., & McDowell, J J. (2009). A Computational Model of Adaptive Behavior Dynamics. Emory University, Department of Psychology, Annual Research Festival. Atlanta, GA",
        date: "05/02/2009",
        type: 'invited talk',
        authors: ["Popa & McDowell (2009)"],
        keywords: ["ETBD", "conference", "Emory University", "evolutionary dynamics", "computational modelling", "complex systems", "emergence"],

        urls: [],

        abstract: "<b>Mathematical</b> models <b>describe</b> the behavior of biological agents in specific environments. <b>Computational</b> theories are essentially computer programs that implement algorithms that <b>generate</b> behavior. The algorithms implement theoretical assumptions about how learning works in biological agents. Mathematical models can be used to verify these assumptions.",
    },



    {
        citation:
            "Popa, A., & McDowell, J J. (2009). Hamming cliffs in a computational model of selection by consequences. Poster presented at the 32nd Annual Meeting of the Society for the Quantitative Analysis of Behavior, Phoenix, AZ.",
        date: "05/21/2009",
        type: "poster",
        authors: ["Popa & McDowell (2009)"],
        keywords: ["Hamming", "ETBD", "changeovers", "sensitivity", "matching"],
        urls: [
            { name: "SQAB 2009", link: "https://www.sqab.org/programs/2009.pdf" },
        ],
        abstract: "McDowell et. al. (2008) hypothesized that the Hamming distance between the target classes may be functionally equivalent to a changeover delay. Exploring this parallel became the topic of my Masters' thesis.",
    },



    {
        citation:
            "Popa, A., & McDowell, J J. (2010). Effects of overall absolute reinforcement rate in a computational model of selection by consequences. Poster presented at the 33rd Annual Meeting of the Society for the Quantitative Analysis of Behavior, San Antonio, Texas.",
        date: "05/28/2010",
        type: "poster",
        authors: ["Popa & McDowell (2010)"],
        keywords: [],
        urls: [
            { name: "SQAB 2010", link: "https://www.sqab.org/programs/2010.pdf" },
        ],

        abstract: "McDowell and Popa (in press) showed that when running concurrent schedules, experimental settings designed to reasonably sample the reinforcement ratio domain may not adequately sample the absolute reinforcement rate domain.  For example, a concurrent RI 10 RI 20 has a reinforcement ratio of 2:1, equal to a concurrent RI 100 RI 200; evidently, the absolute reinforcement rates differ considerably. McDowell and Popa suggested that the overall absolute reinforcement rate in a concurrent schedule might affect behavior generated by the computational model. Systematic and thorough sampling of the absolute reinforcement rate domain in a series of computational experiments confirmed this hypothesis. <b>The results</b> showed that as the overall absolute reinforcement rate increased, behavior generated by the computational model became less sensitive to changes in parameters related to reinforcer value, changeover delay, and impulsivity.",
    },



    {
        citation:
            "Popa, A., & McDowell, J J. (2010). Evolutionary Behavior Dynamics causally generates both molar and molecular properties of behavior. Symposium: The Molar-Molecular debate: A further discussion on the unresolved issue. Discussant: William M. Baum, Ph.D. Presented at the 36th Annual Convention of the Association for Behavior Analysis International, San Antonio, TX.", date: "05/31/2010",
        type: "invited talk",
        authors: ["Popa & McDowell (2010)"],
        role: "invited talk",
        tags: ["problem framing"],
        keywords: ["ABAI", "invited talk", "conference"],
        description: "ETBD was shown to generate behavior consistent with that of living organisms at both molar and molecular lever. This suggests that both molar and molecular properties are natural consequences of evolutionary dynamics, which cancels the need for molar and molecular views",

        urls: [
            { name: "ABAI 2010", link: "https://www.abainternational.org/events/program-details/event-detail.aspx?sid=8950&by=ByArea#s436_0" },
        ],
        abstract:
            "Both molar and molecular causality may be illusory. Molar and molecular features of behavior are emergent properties of an evolutionary theory of behavior dynamics that instantiates the idea that behavior evolves in response to selection pressure provided by reinforcement from the environment. This theory consists of Darwinian rules of selection, reproduction, and mutation that operate on a population of potential behaviors over time to generate a continuous stream of emitted behavior. The evolutionary theory has been shown to generate behavior on single random interval (RI) and concurrent RI RI schedules that has molar properties consistent with matching theory, and that are quantitatively indistinguishable from molar properties of live-organism behavior. At the same time, the theory has been shown to generate molecular inter-response time (IRT) distributions that can be studied in the form of log-survivor plots, and that are similar to log-survivor IRT distributions from live organisms. A parallel selectionist theory of neural functioning has been discussed as a plausible material mechanism for this evolutionary theory of behavior dynamics.",
    },


    {
        citation: "Popa, A., & McDowell, J J. (2011). A Computational Model of Selection by Consequences: Effects of the changeover delay (COD) on the impulsive behavior of a virtual organism. Poster presented at the 34th Annual Meeting of the Society for the Quantitative Analysis of Behavior, Denver, CO.",
        date: "04/10/2011",
        type: "poster",
        authors: ["Popa & McDowell (2011)"],
        keywords: ["etbd", "adhd", "impulsivity", "cod", "hamming", "mutation"],
        tags: [],

        urls: [
            { name: "SQAB 2011", link: "https://www.sqab.org/programs/2011.pdf" },
        ],
        abstract: "abstract must be typed, cannot be copied.",
    },



    {
        citation:
            "Popa, A., & McDowell, J J. (2011). A Computational Model of Selection by Consequences: Evidence that Mutation is Computationally Equivalent to Impulsivity. Paper presented at the 37th Annual Convention of the Association for Behavior Analysis International, Denver, CO.",
        date: "05/30/2011",
        type: "talk",
        authors: ["Popa & McDowell (2011)a", "Popa & McDowell (2011)b"],
        keywords: ["ABAI 2011", "ETBD", "ADHD"],
        urls: [
            { name: "SQAB 2011", link: "https://www.sqab.org/programs/2011.pdf" },
            {
                name: "ABAI 2011",
                link: "https://www.abainternational.org/events/program-details/event-detail.aspx?sid=13494&by=ByArea#s445_0",
            },

        ],
        abstract:
            "The present experiments systematically investigated the effects of various mutation levels, rates of reinforcement, changeover delay (COD) values, and reinforcers' magnitudes on the behavior of the virtual organism on concurrent RI RI schedules. The purpose was twofold: to clarify the parallel between mutation and impulsivity and to explore methods of counteracting the undesired effects of high mutation rates. The results showed that improved performance in concurrent-schedules performance (e.g. increased sensitivity to reinforcement, reduced rate of switching, etc.) under high levels of mutation is attainable by increasing the rate or magnitude of the reinforcement and/or the COD requirement; the results accurately parallel those reported in the attention deficit/hyperactivity disorder literature (Kollins, Lane, and Shapiro, 1997; Aase and Sagvolden, 2006; Taylor, Lincoln, and Foster, 2010), indicating that mutation is the computational equivalent of impulsivity.",
    },




    {
        citation:
            "Popa, A., & McDowell, J J. (2012). The Computational Theory of Behavior Dynamics Predicts Effects of COD on Behavioral Variability: Evidence from experiments with human participants. Paper presented at the 38th Annual Convention of the Association for Behavior Analysis International, Seattle, WA.",
        date: "05/26/2012",
        type: "talk",
        authors: ["Popa & McDowell (2012)"],
        keywords: [],
        urls: [
            {
                name: "ABAI 2012",
                link: "https://www.abainternational.org/events/program-details/event-detail.aspx?sid=17728&by=ByArea#s28_0",
            },
            {
                name: "ResearchGate",
                link: "https://www.abainternational.org/events/program-details/event-detail.aspx?sid=17728&by=ByArea#s28_0",
            },
        ],
        abstract:
            "Popa and McDowell (2010) showed that the Hamming Distance, a particular mathematical feature of McDowell’s Evolutionary Theory of Behavior Dynamics (ETBD; McDowell, 2004, 2010) is computationally equivalent to the changeover delay (COD; Findley, 1954) used in experiments with live organisms. Popa and McDowell (2011) suggested that increasing the computational COD requirement reduces behavioral variability in a virtual organism animated by the ETBD. The present paper further investigated a wide range of computational COD values and used the results to formulate predictions about the effects of COD requirements on the behavioral variability of humans in concurrent-schedules environments. As predicted by ETBD, the rate of switching between alternatives was systematically decreased by increased COD requirements. These results provide further support for the ETBD as a valid account of behavior dynamics, showing that it is not only able to produce outcomes congruent with known behavior statics (the Matching Law; McDowell & Popa, 2010), but it can also formulate predictions about the behavior of live organisms. Moreover, these findings suggest that high behavioral variability may be a natural outcome of the selection pressure exerted by unstructured environments. The implications for ADHD-symptoms are discussed within the framework provided by previous research (Neuringer, 2010; Taylor et al, 2010).",
    },


    {
        citation:
            "Popa, A., Calvin, N., & McDowell, J J. (2013). Complexity, Emergence, and the Behavior of Organisms. Paper presented at the 39th Annual Convention of the Association for Behavior Analysis International, Minneapolis, MN.",
        date: "05/26/2013",
        type: "talk",
        authors: ["Popa, Calvin, & McDowell (2013)"],
        keywords: [],
        urls: [
            {
                name: "ABAI 2013",
                link: "https://www.abainternational.org/events/program-details/event-detail.aspx?sid=28880&by=ByArea#s166_0",
            },
        ],
        abstract: "Complexity science is rapidly becoming the 'spoiled child' of the scientific community, promising to dissolve interdisciplinary barriers and open a new chapter in our understanding of the natural world (Mitchell, 2009). Complex systems are dynamic, adaptive systems, composed from a large number of interconnected parts, and governed by simple, low-level rules that can give rise to novel, emergent features or behaviors. High-level, emergent properties are not readily reducible to the rules that produce them. They appear to be stand-alone entities and behavioral and psychological sciences have traditionally studied them as such (e.g. impact of divorce on children's risk of depression). However, if they are emergent features of a dynamic system, the relations between them cannot, in principle, be causal (divorce → depression). Their co-occurrence is incidental, both being produced by underlying simple rules reiterated over long periods of time. In order to fully understand an emergent property, one must identify the rules that govern the system and the specific conditions under which the property emerges (McDowell & Popa, 2009). This implies a complete shift in focus, from high-level properties to low-level rules and characteristics, opening a fascinating doorway for scholars interested in the behavior of organisms.",
    },



    {
        citation:
            "Popa, A., Calvin, N., & McDowell, J J. (2014). Multifinality and Equifinality in an Evolutionary Theory of Behavior Dynamics. Paper presented at the 40th Annual Convention of the Association for Behavior Analysis International, Chicago, IL.",
        date: "05/24/2014",
        type: "talk",
        authors: ["Popa, Calvin, & McDowell (2014)"],
        keywords: ["ABAI 2014", "causation", "complexity"],
        urls: [
            {
                name: "ABAI 2014",
                link: "https://www.abainternational.org/events/program-details/event-detail.aspx?sid=40586&by=ByArea#s30_0",
            },
        ],
        abstract:
            "Skinner (1981) suggested that natural selection operates not only at the biological level, but is also responsible for the evolution of behavioral repertoires throughout an organism’s lifetime. McDowell (2004) implemented the selectionist account in a computational theory of behavior dynamics. The theory causes a population of behaviors to evolve through time under the selection pressure exerted by the environment. It has been tested under a variety of conditions and the emergent outcomes were repeatedly  shown to be qualitatively and quantitatively indistinguishable from those displayed by live organisms (McDowell, in press). The present project investigated the effects of various environmental variables (e.g. reward magnitude) on the behavior variability of virtual organisms characterized by various mutation rates. High mutation rates produced behavioral constellations similar to those displayed by ADHD-diagnosed children. These effects were counteracted by arranging richer or more structured environments (higher changeover delay). Interestingly, arranging low-value environments caused organisms characterized by low mutation rates to display abnormally high levels of variability. These findings suggest that similar high-level phenotypes such ADHD may be caused by various combinations of organismic and environmental features (equifinality), during a dynamic process governed by Darwinian forces.",
    },




    {
        citation:
            "Popa, A. (2015). Towards an Evolutionary Account for the Dynamics of Cognizant Systems. Darwin Day Lecture Series, Georgia State University, Atlanta, GA.",
        date: "02/13/2015",
        type: "invited talk",
        authors: ["Popa (2015)"],
        keywords: ["Darwin2015", "invited talk", "conference"],
        urls: [],
        abstract: "Before Darwin, biology was dominated by essentialism,  the view that each species has an immutable prototype, an ideal form from which all individuals depart to some extent. Darwins insight, now known as population thinking, was that ideal forms do not exist and averages are illusions. The phenotipic diversity in a population is not imperfection, or decay, but its natural state. We have a similar problem in psychology.<br/><br/><br/><br/><br/><br/><br/><br/>",
    },



    {
        citation:
            "Popa, A. (2016). Population Thinking, Psychodiversity, and Human Development. Darwin Day Lecture Series, Georgia State University, Atlanta, GA.",
        date: "02/09/2016",
        type: "invited talk",
        authors: ["Popa (2016)"],
        keywords: ["Darwin2016", "invited talk", "conference"],
        urls: [],
        abstract: "Darwin proposed that the biodiversity we observe today emerged gradually, from a common root, by means of natural selection: when individuals reproduce, they pass on their genes. Those who reproduce more often will pass on more copies of their genetic material. Adaptation, therefore, is a byproduct of sexual reproduction. <br/><br/><br/><br/><br/><br/><br/><br/>",
    },



    //------------------------------------
    {
        id: "[20]",
        authors: "<sup>U</sup>Adekunle & Popa (2016)",
        type: 'research poster',
        keywords: "keywords",
        citation: "<sup>U</sup>Adekunle, O. & Popa, A. (2016). <i>Higher Payoff or More Options? Poster presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.",
    },


    {
        id: "[21]",
        authors: "<sup>U</sup>Booher & Popa (2016)",
        type: 'research poster',
        keywords: "keywords",
        citation: "<sup>U</sup>Booher, C. & Popa, A. (2016). <i>Choice Behavior in Unsignaled Environments With and Without Immediate Negative Feedback. Poster presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.",
    },


    {
        id: "[22]",
        authors: "<sup>U</sup>Forbes & Popa (2016)",
        type: 'research poster',
        citation: "<sup>U</sup>Forbes, V., & Popa, A. (2016). <i>Human Choice Behaviors Before and After Extinction. Poster presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.",
        keywords: "keywords",
    },

    {
        id: "[17]",
        authors: "<sup>U</sup>Grissom & Popa (2016)",
        type: 'talk',
        keywords: "keywords",
        citation: "<sup>U</sup>Grissom, M. K., & Popa, A. (2016). <i>Effects of Extinction on Human Escape Behavior. Paper presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.",
    },


    {
        id: "[18]",
        authors: "<sup>U</sup>Shen & Popa (2016)",
        type: 'talk',
        keywords: "keywords",
        citation: "<sup>U</sup>Shen, R. & Popa, A. (2016). <i>Is Competition Sufficient to Increase the Motivation to “Do Well”</i>? Paper presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.",
    },

    {
        id: "[23]",
        authors: "<sup>U</sup>Tang & Popa (2016)",
        type: 'research poster',
        citation: "<sup>U</sup>Tang, X., & Popa, A. (2016). <i>Choice Behavior in Low Discriminability Conditions: Effects of the Operant Class Size. Poster presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.",
        keywords: "keywords",
    },

    {
        id: "[19]",
        authors: "<sup>U</sup>Waithe & Popa (2016)",
        type: 'paper',
        keywords: "keywords",
        citation: "<sup>U</sup>Waithe, O. Y., & Popa, A. (2016). <i>The Effects of Imagery on Psychological Discomfort</i>. Paper presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.",
    },



    // {
    //     id: 22,
    //     title: "Fast Matching procedures adapted ",
    //     date: "04/01/2016",
    //     type: "research study, human choice",
    //     time: "04/01/2016",
    //     role: "STUDY COORDINATOR",
    //     authors: [
    //         "<sup>U</sup>Adekunle & Popa (2016)",
    //         "<sup>U</sup>Booher & Popa (2016)",
    //         "<sup>U</sup>Forbes & Popa (2016)",
    //         "<sup>U</sup>Grissom & Popa (2016)",
    //         "<sup>U</sup>Shen & Popa (2016)",
    //         "<sup>U</sup>Tang & Popa (2016)",
    //         "<sup>U</sup>Waithe & Popa (2016)",
    //     ],
    //     keywords: ["Agnes Scott College"],
    //     tags: ["VB.Net"],
    //     description: "",
    //     // description:
    //     //   "My second opportunity to run my own lab. ... (Senior Seminar, Choice and Preference) ... Stimulus control and negative reinforcement in humans. ...The students from my senior seminar on The Dynamics of Choice and Preference contributed three talks and four posters to the Spring Annual Research Conference. Managing this enterprise would have been challenging at best without my research assistants - Alessandra Xi Zhang and Olivia Zivot, to whom I am grateful.",

    //     urls: [
    //         { name: "SpARC", link: "https://www.agnesscott.edu/sparc/index.html" },
    //         { name: "SpARC INDEX", link: "https://www.agnesscott.edu/sparc/" },
    //     ],
    //     citation:
    //         "The Spring Annual Research Conference is held at Agnes Scott each April to provide students and faculty with an opportunity to present their work to the campus community. As an interdisciplinary conference, SpARC fosters essential connections across academic disciplines and encourages an ongoing dialogue between the liberal arts and sciences.",
    //     abstract: "The Spring Annual Research Conference is held at Agnes Scott each April to provide students and faculty with an opportunity to present their work to the campus community.As an interdisciplinary conference, SpARC fosters essential connections across academic disciplines and encourages an ongoing dialogue between the liberal arts and sciences. My mentees (bold font) and I contributed five (5) posters and three (3) talks, counting towards ~15% of all research projects presented at SpARC 2016. Note that all eight were novel contributions to the field. I would like to take this opportunity to thank my former students and research assistants, AlessandraXi Zhangand Olivia Zivot. Without their contribution, managing this enterprise would have been challenging at best.",
    //     // citations:
    //     //     "Adekunle, O. & Popa, A. (2016). Higher Payoff or More Options? Poster presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA. <br/> Booher, C. & Popa, A. (2016). Choice Behavior in Unsignaled Environments With and Without Immediate Negative Feedback. Poster presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.<br/> Forbes, V., & Popa, A. (2016). Human Choice Behaviors Before and After Extinction. Poster presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.<br/> Grissom, M. K., & Popa, A. (2016). Effects of Extinction on Human Escape Behavior. Paper presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.<br/> Shen, R. & Popa, A. (2016). Is Competition Sufficient to Increase the Motivation to “Do Well”? Paper presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.<br/> Tang, X., & Popa, A. (2016). Choice Behavior in Low Discriminability Conditions: Effects of the Operant Class Size. Poster presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.<br/> Waithe, O. Y., & Popa, A. (2016). The Effects of Imagery on Psychological Discomfort. Paper presented at the Spring Annual Research Conference, Agnes Scott College, Decatur, GA.",
    // },


    {
        citation:
            "Popa, A. & Grissom, M. K. (2017). Extinction-Induced Variability on Negatively Reinforced Human Behavior. Paper presented at the Winter Conference on Animal Learning & Behavior, Park City, UT.",
        date: "02/19/2017",
        type: "talk",
        authors: ["Popa & Grissom (2017)"],

        keywords: ["WCALB 2017", "talk", "conference", "Utah"],


        urls: [
            {
                name: "WCALB 2017",
                link: "https://static1.squarespace.com/static/57b732f259cc68697145ea01/t/5b7dbd231ae6cf8700f3d604/1534967075831/Past+Programs+2017.pdf",
            },
        ],



        abstract:
            "When a previously reinforced behavior suddenly becomes ineffective, it will eventually disappear from an organism’s repertoire. Its extinction, however, is often preceded by an extinction burst: a short-lived period of frenetic activity, during which the targeted behavior increases in frequency, intensity, and variability, and often accompanied by the presence of novel behaviors. The effects of extinction on behavioral variability have been mostly investigated in the context of positively reinforced behaviors. In this paper, we explored its effects on the frequency and variability of negatively reinforced human behavior. Extinction caused a ten-fold increase in behavior frequency, high changeover frequency, a surge in the frequency of extraneous behavior, and higher inter-response variability, in both time and space. These results suggested, among other things, that negatively reinforced behavior was inherently variable, that behavioral novelty observed during extinction may have had little adaptive potential (if any), and that negative reinforcement may have stifled exploratory tendencies.",

    },

    {
        citation:
            "Popa, A., (2017). Towards a Dynamic Account of Human Development. Paper presented at the 43rd Annual Convention of the Association for Behavior Analysis International, Denver, CO.",
        date: "05/28/2017",
        type: "talk",
        authors: ["Popa (2017)"],

        keywords: ["ABAI 2017", "talk", "conference"],

        urls: [
            {
                name: "ABAI 2017",
                link: "https://www.abainternational.org/events/program-details/event-detail.aspx?sid=53139&by=ByArea#s196_0",
            },
            {
                name: "Conference schedule",
                link: "https://www.abainternational.org/events/annual-2017.aspx",
            },
        ],


        abstract:
            "The biopsychosocial model acknowledges that high-level phenotypes (e.g., impulsivity, good at math, etc.) are multiply-caused by a plethora of contributing, interacting factors, such as specific genetic configurations, socio-economic status, culture, ethnicity, gender, and so on.  However, the model does not explain how these variables interact with each other or how, exactly, they contribute to a specific outcome. I submit to the reader a potential explanation. Drawing on theoretical advancements from the field of complex systems and on computational research on the dynamics of behavioral repertoires (McDowell, 2013; Popa, 2013; Popa & McDowell, 2016), the theory discussed here proposes that the interaction between agents and their environment consists of a continuous-choice process during which agents adapt to environmental changes. This process molds an individual’s context (e.g., income, culture, etc.) into robust collections of cognitive, emotional, and behavioral manifestations like “impulsivity”, “authoritative parent”, etc. The factors typically associated with impulsivity (for example) contribute to its emergence indirectly, by altering the relative value of existing options, and, by extension, the moment-to-moment probability of choosing one course of action over another. High-level phenotypes, therefore, cannot be directly explained by the contributing factors themselves, but by the moment-to-moment changes said factors produce in cognition and action.",
    },

];

export default infoConferences;
