
import React, { Component } from "react";
import parse from "html-react-parser";

import MatchingDemo from "../matching/MatchingDemo.js";
//import ETBD from "../etbd/ETBD.js"


import "./chapters.sass"

class Chapter01 extends Component {
    render() {
        var skills = [
            "Excel/VBA",
            "syntethic data",
            "research design",
            "hypothesis testing",
            "exploratory analysis",
            "model selection",
            "ensemble fitting",
            "residual analysis",
            "regression analysis",
        ];

        var Skills = skills.map((s) => {
            return <label key={s}>{s}</label>;
        });

        return (
            <div
                id="ch01"
                className="chapter"
                style={{ backgroundColor: "#1D2731", }}>

                <div className="chapterRow">
                    <div className="chapterCol">

                        {/* <span className="spanYears">2011 - 2013</span> */}

                        {/* <span
                            className="spanYears"
                            style={{
                                //backgroundColor: "#233d46",
                                marginBottom: "1rem",
                                paddingLeft: "0rem",
                                color: "#ccc"
                            }}
                        >2007 - 2010</span> */}


                        {/* <h1 className="chapter-title" style={{ fontSize: "2.2rem", marginBottom: "2rem" }}>Learning, ETBD, and me</h1> */}

                        <p id="ch01_p1" className="p-left" style={{ border: "1px solid #fff", padding: "1rem" }}>
                            In 2007 I joined Dr. McDowell's lab of computational behavior analysis. For the next six years I studied the dynamics of choice and preference. Until 2011, when I expanded my research to human behavior, I worked exclusively with synthetic data generated by an evolutionary theory of behavior dynamics, or ETBD (McDowell, 2004). Before we get into it, let's see what it's supposed to explain.
                        </p>

                        <h1 className="chapter-title" style={{ fontSize: "1.5rem", margin: "2rem 0rem 1rem 0rem" }}>Choice & preference</h1>

                        <p id="ch01_p3" className="p-left">
                            Check out the demo on the right. The experimental environment is a so-called Skinner-box - an experimental chamber used to study the relation between behavior, consequences, and context in living agents. The top half is a <i>cumulative record</i>, a graph that plots the cumulative response frequency as a function of time.
                        </p>


                        <h2 className="chapter-title" style={{ fontSize: "1.5rem", margin: "2rem 0rem 1rem 0rem" }}>ETBD</h2>

                        <p className="p-left">
                            In ETBD, behaviors are represented by numbers, response classes are ranges, and 'agents' are populations of numbers that are transformed, generation after generation, by local rules of <span style={{ color: 'yellow' }} >selection</span>, <span style={{ color: 'yellow' }} >recombination</span>, and <span style={{ color: 'yellow' }} >mutation</span>.
                        </p>

                        <p className="p-left">{parse("For verification, the emerging patterns are compared with those exhibited by living agents under similar experimental conditions.")}</p>

                        <div className="chapterSkills">{Skills}</div>

                    </div>



                    <div className="chapterCol">
                        <div className="projectColumnImagesMatching">
                            <MatchingDemo />
                            {/* <ETBD /> */}
                        </div>
                    </div>


                </div>
            </div>
        );
    }
}

export default Chapter01;
